AI_TEAM_POOL = [{'name': 'Blood Current',
  'usage': 'Roland anchors, Hunold shocks, and Risa converts the softened frontline into fast kills. This is a clean '
           'pressure team that snowballs once Risa hits bloodied thresholds.',
  'members': [{'defn': 'risa_redcloak', 'sig': 'crimson_fury', 'basics': ['rend', 'cleave']},
              {'defn': 'hunold_the_piper', 'sig': 'haunting_rhythm', 'basics': ['post_bounty', 'sucker_punch']},
              {'defn': 'sir_roland', 'sig': 'shimmering_valor', 'basics': ['shield_bash', 'stalwart']}],
  'artifacts': ['excalibur', 'holy_grail', 'red_hood']},
 {'name': 'Tempo Chapel',
  'usage': 'Hare controls tempo, Aldric keeps Jack upright, and Jack does the actual breaking. Use buffs and healing '
           'to force repeated Skyfall turns.',
  'members': [{'defn': 'little_jack', 'sig': 'skyfall', 'basics': ['strike', 'cleave']},
              {'defn': 'march_hare', 'sig': 'tempus_fugit', 'basics': ['thunder_call', 'ominous_gale']},
              {'defn': 'aldric_lost_lamb', 'sig': 'benefactor', 'basics': ['heal', 'bless']}],
  'artifacts': ['winged_sandals', 'achilles_spear', 'bluebeards_key']},
 {'name': 'Rootbreaker Court',
  'usage': 'Layer Root and Weaken early, then trap enemy movement until Green Knight can pin the frontline duel. '
           'Excellent into swap-reliant teams.',
  'members': [{'defn': 'gretel', 'sig': 'shove_over', 'basics': ['intimidate', 'cleave']},
              {'defn': 'briar_rose', 'sig': 'thorn_snare', 'basics': ['trapping_blow', 'volley']},
              {'defn': 'green_knight', 'sig': 'heros_bargain', 'basics': ['edict', 'command']}],
  'artifacts': ['cursed_needle', 'magic_mirror', 'nettle_smock']},
 {'name': 'Phantom Carriage',
  'usage': 'Constantine exposes, Ella spreads burn, and Pinocchio scales while opponents lose clean lines. This team '
           'wins by making backline positions unsafe.',
  'members': [{'defn': 'lucky_constantine', 'sig': 'feline_gambit', 'basics': ['post_bounty', 'sucker_punch']},
              {'defn': 'ashen_ella', 'sig': 'crowstorm', 'basics': ['fire_blast', 'ominous_gale']},
              {'defn': 'pinocchio', 'sig': 'wooden_wallop', 'basics': ['dark_grasp', 'blood_pact']}],
  'artifacts': ['last_prism', 'melusines_knife', 'selkies_skin']},
 {'name': 'Marked Quarry',
  'usage': 'Mark targets with Spotlight/Expose/defense drops, then let Robin and Reynard pick off whatever gets '
           'revealed. Strong into fragile backline carries.',
  'members': [{'defn': 'reynard', 'sig': 'size_up', 'basics': ['sneak_attack', 'post_bounty']},
              {'defn': 'robin_hooded_avenger', 'sig': 'snipe_shot', 'basics': ['hawkshot', 'hunters_badge']},
              {'defn': 'prince_charming', 'sig': 'condescend', 'basics': ['decree', 'command']}],
  'artifacts': ['winged_sandals', 'excalibur', 'magic_mirror']},
 {'name': 'Kiln And Sea',
  'usage': 'Porcus soaks, Witch spreads statuses, and Asha turns debuffs into real kill pressure. Very punishing in '
           'long games.',
  'members': [{'defn': 'porcus_iii', 'sig': 'not_by_the_hair', 'basics': ['shield_bash', 'stalwart']},
              {'defn': 'witch_of_the_woods', 'sig': 'toil_and_trouble', 'basics': ['fire_blast', 'ominous_gale']},
              {'defn': 'sea_wench_asha', 'sig': 'abyssal_call', 'basics': ['dark_grasp', 'soul_gaze']}],
  'artifacts': ['cursed_needle', 'misericorde_artifact', 'golden_fleece']},
 {'name': 'Avalon Hunt',
  'usage': 'Lady and Frederic create direct frontline pressure while Rumpel taxes any buff-heavy enemy team. Great at '
           'forcing straightforward fights.',
  'members': [{'defn': 'lady_of_reflections', 'sig': 'drown_in_the_loch', 'basics': ['shield_bash', 'condemn']},
              {'defn': 'frederic', 'sig': 'heros_charge', 'basics': ['hawkshot', 'hunters_badge']},
              {'defn': 'rumpelstiltskin', 'sig': 'name_the_price', 'basics': ['blood_pact', 'cursed_armor']}],
  'artifacts': ['achilles_spear', 'holy_grail', 'bluebeards_key']},
 {'name': 'Radiant Briars',
  'usage': 'This is a survival-control shell. Rapunzel roots and disrupts, while Liesl and Aurora keep tempo from '
           'collapsing.',
  'members': [{'defn': 'matchstick_liesl', 'sig': 'cinder_blessing', 'basics': ['heal', 'bless']},
              {'defn': 'snowkissed_aurora', 'sig': 'toxin_purge', 'basics': ['heal', 'medic']},
              {'defn': 'rapunzel', 'sig': 'golden_snare', 'basics': ['edict', 'impose']}],
  'artifacts': ['divine_apple', 'bluebeards_key', 'godmothers_wand']},
 {'name': 'Pursuit Lock',
  'usage': 'Taunt and Spotlight create ugly action patterns, then Risa punishes swaps and exposed follow-ups. It is '
           'especially strong against reactive players.',
  'members': [{'defn': 'risa_redcloak', 'sig': 'wolfs_pursuit', 'basics': ['feint', 'intimidate']},
              {'defn': 'hunold_the_piper', 'sig': 'dying_dance', 'basics': ['sucker_punch', 'fleetfooted']},
              {'defn': 'sir_roland', 'sig': 'knights_challenge', 'basics': ['condemn', 'stalwart']}],
  'artifacts': ['last_prism', 'excalibur', 'red_hood']},
 {'name': 'Storm Chapel',
  'usage': 'Hare manufactures extra actions and Jack abuses them. Aldric turns the midgame into a resource war that '
           'favors your burst windows.',
  'members': [{'defn': 'little_jack', 'sig': 'belligerence', 'basics': ['cleave', 'feint']},
              {'defn': 'march_hare', 'sig': 'rabbit_hole', 'basics': ['arcane_wave', 'breakthrough']},
              {'defn': 'aldric_lost_lamb', 'sig': 'sanctuary', 'basics': ['heal', 'protection']}],
  'artifacts': ['winged_sandals', 'goose_quill', 'holy_grail']},
 {'name': 'Oven Garden',
  'usage': 'Burn plus Root plus anti-swap pressure makes this team miserable to navigate. Use Green Knight to punish '
           'enemies who try to sit still.',
  'members': [{'defn': 'gretel', 'sig': 'hot_mitts', 'basics': ['strike', 'rend']},
              {'defn': 'briar_rose', 'sig': 'creeping_doubt', 'basics': ['hunters_mark', 'trapping_blow']},
              {'defn': 'green_knight', 'sig': 'natural_order', 'basics': ['decree', 'command']}],
  'artifacts': ['cursed_needle', 'misericorde_artifact', 'magic_mirror']},
 {'name': 'Puppet Midnight',
  'usage': 'Reposition enemies with Constantine, let Ella absorb tempo awkwardly, and cash in with Pinocchio\'s '
           'expose-driven spikes. High ceiling and slippery.',
  'members': [{'defn': 'lucky_constantine', 'sig': 'subterfuge', 'basics': ['sneak_attack', 'post_bounty']},
              {'defn': 'ashen_ella', 'sig': 'midnight_dour', 'basics': ['arcane_wave', 'breakthrough']},
              {'defn': 'pinocchio', 'sig': 'cut_the_strings', 'basics': ['soul_gaze', 'cursed_armor']}],
  'artifacts': ['melusines_knife', 'selkies_skin', 'last_prism']},
 {'name': 'Royal Crossfire',
  'usage': 'Reynard and Charming manipulate focus while Robin turns spread pressure into reliable chip. Best when you '
           'play patiently and punish overcommitment.',
  'members': [{'defn': 'reynard', 'sig': 'feign_weakness', 'basics': ['riposte', 'fleetfooted']},
              {'defn': 'robin_hooded_avenger', 'sig': 'spread_fortune', 'basics': ['volley', 'hunters_mark']},
              {'defn': 'prince_charming', 'sig': 'gallant_charge', 'basics': ['summons', 'decree']}],
  'artifacts': ['winged_sandals', 'excalibur', 'magic_mirror']},
 {'name': 'Boiling Deep',
  'usage': 'Porcus creates a safe board for Witch to spread statuses. Asha steals whatever the matchup gives her and '
           'converts stalled boards into advantage.',
  'members': [{'defn': 'porcus_iii', 'sig': 'porcine_honor', 'basics': ['armored', 'stalwart']},
              {'defn': 'witch_of_the_woods', 'sig': 'cauldron_bubble', 'basics': ['fire_blast', 'thunder_call']},
              {'defn': 'sea_wench_asha', 'sig': 'misappropriate', 'basics': ['dark_grasp', 'blood_pact']}],
  'artifacts': ['golden_fleece', 'cursed_needle', 'holy_grail']},
 {'name': 'Trial By Gold',
  'usage': 'This team wins incremental exchanges. Frederic buffs himself, Rumpel amplifies those stats, and Lady makes '
           'every enemy KO trade uncomfortable.',
  'members': [{'defn': 'lady_of_reflections', 'sig': 'postmortem_passage', 'basics': ['shield_bash', 'stalwart']},
              {'defn': 'frederic', 'sig': 'on_the_hunt', 'basics': ['hunters_mark', 'hunters_badge']},
              {'defn': 'rumpelstiltskin', 'sig': 'straw_to_gold', 'basics': ['dark_grasp', 'soul_gaze']}],
  'artifacts': ['achilles_spear', 'winged_sandals', 'godmothers_wand']},
 {'name': 'Ashen Lullaby',
  'usage': 'Rapunzel softens targets while the double-cleric core refuses to die. Excellent into attrition and '
           'status-heavy teams.',
  'members': [{'defn': 'matchstick_liesl', 'sig': 'flame_of_renewal', 'basics': ['heal', 'protection']},
              {'defn': 'snowkissed_aurora', 'sig': 'dictate_of_nature', 'basics': ['smite', 'heal']},
              {'defn': 'rapunzel', 'sig': 'lower_guard', 'basics': ['impose', 'decree']}],
  'artifacts': ['bluebeards_key', 'divine_apple', 'nettle_smock']},
 {'name': 'Blood Ledger',
  'usage': 'This is a durable pressure team with nasty turn redirection. Use Roland\'s passive to farm guarded swaps, '
           'then let Risa force HP swings.',
  'members': [{'defn': 'risa_redcloak', 'sig': 'blood_hunt', 'basics': ['strike', 'rend']},
              {'defn': 'hunold_the_piper', 'sig': 'hypnotic_aura', 'basics': ['post_bounty', 'fleetfooted']},
              {'defn': 'sir_roland', 'sig': 'banner_of_command', 'basics': ['shield_bash', 'armored']}],
  'artifacts': ['holy_grail', 'red_hood', 'enchanted_lamp']},
 {'name': 'Cloudburst Loop',
  'usage': 'Hare sets up burst sequencing, Jack roots key pieces, and Aldric stabilizes the front while adding '
           'lifesteal utility. Strong tempo-burst hybrid.',
  'members': [{'defn': 'little_jack', 'sig': 'beanstalk_crash', 'basics': ['strike', 'intimidate']},
              {'defn': 'march_hare', 'sig': 'nebulous_ides', 'basics': ['breakthrough', 'arcane_wave']},
              {'defn': 'aldric_lost_lamb', 'sig': 'repentance', 'basics': ['smite', 'heal']}],
  'artifacts': ['goose_quill', 'achilles_spear', 'holy_grail']},
 {'name': 'Crumb Kingdom',
  'usage': 'This team weaponizes movement. Every swap, attack line, and frontline approach can be punished by Briar or '
           'Green Knight while Gretel feeds sustain.',
  'members': [{'defn': 'gretel', 'sig': 'crumb_trail', 'basics': ['feint', 'cleave']},
              {'defn': 'briar_rose', 'sig': 'garden_of_thorns', 'basics': ['volley', 'trapping_blow']},
              {'defn': 'green_knight', 'sig': 'awaited_blow', 'basics': ['impose', 'command']}],
  'artifacts': ['magic_mirror', 'cursed_needle', 'red_hood']},
 {'name': 'Smoke At Midnight',
  'usage': 'Ella and Pinocchio scale board control while Constantine acts as an annoying pseudo-anchor. Good into '
           'burst teams that rely on clean one-round kills.',
  'members': [{'defn': 'lucky_constantine', 'sig': 'nine_lives', 'basics': ['fleetfooted', 'riposte']},
              {'defn': 'ashen_ella', 'sig': 'fae_blessing', 'basics': ['fire_blast', 'ominous_gale']},
              {'defn': 'pinocchio', 'sig': 'become_real', 'basics': ['dark_grasp', 'void_step']}],
  'artifacts': ['enchanted_lamp', 'selkies_skin', 'last_prism']},
 {'name': 'Fox\'s Coronation',
  'usage': 'Charming creates a protected carry, Reynard steals speed and repositions, and Robin turns that into '
           'focused elimination. Very good at midgame collapse turns.',
  'members': [{'defn': 'reynard', 'sig': 'cutpurse', 'basics': ['sneak_attack', 'fleetfooted']},
              {'defn': 'robin_hooded_avenger', 'sig': 'bring_down', 'basics': ['hawkshot', 'trapping_blow']},
              {'defn': 'prince_charming', 'sig': 'chosen_one', 'basics': ['command', 'summons']}],
  'artifacts': ['winged_sandals', 'excalibur', 'godmothers_wand']},
 {'name': 'Fortress Sabbath',
  'usage': 'Let Porcus or his ally absorb the first wave, then pile on multi-status punishment through Witch and Asha. '
           'Great into balanced teams.',
  'members': [{'defn': 'porcus_iii', 'sig': 'sturdy_home', 'basics': ['condemn', 'stalwart']},
              {'defn': 'witch_of_the_woods', 'sig': 'crawling_abode', 'basics': ['ominous_gale', 'thunder_call']},
              {'defn': 'sea_wench_asha', 'sig': 'faustian_bargain', 'basics': ['soul_gaze', 'void_step']}],
  'artifacts': ['misericorde_artifact', 'golden_fleece', 'cursed_needle']},
 {'name': 'Avalon Quarry',
  'usage': 'Lady shares her reflection effect, Frederic adds frontline control, and Rumpel turns every buff spread '
           'into scaling damage. Strong against teams that brawl in place.',
  'members': [{'defn': 'lady_of_reflections', 'sig': 'lakes_gift', 'basics': ['shield_bash', 'armored']},
              {'defn': 'frederic', 'sig': 'jovial_shot', 'basics': ['hawkshot', 'volley']},
              {'defn': 'rumpelstiltskin', 'sig': 'spinning_wheel', 'basics': ['dark_grasp', 'soul_gaze']}],
  'artifacts': ['bluebeards_key', 'holy_grail', 'achilles_spear']},
 {'name': 'Tower Wake',
  'usage': 'Use Rapunzel\'s passive positioning tax to shrink enemy output while Liesl blocks healing and Aurora '
           'gradually cleanses and scales birds. Slow but oppressive.',
  'members': [{'defn': 'matchstick_liesl', 'sig': 'cauterize', 'basics': ['smite', 'medic']},
              {'defn': 'snowkissed_aurora', 'sig': 'birdsong', 'basics': ['medic', 'protection']},
              {'defn': 'rapunzel', 'sig': 'ivory_tower', 'basics': ['summons', 'command']}],
  'artifacts': ['divine_apple', 'bluebeards_key', 'nettle_smock']},
 {'name': 'Hit And Run',
  'usage': 'This is one of the cleanest ladder teams. Hare creates action advantage, Roland covers swaps, and Gretel '
           'cashes in on every reposition.',
  'members': [{'defn': 'march_hare', 'sig': 'rabbit_hole', 'basics': ['breakthrough', 'arcane_wave']},
              {'defn': 'sir_roland', 'sig': 'banner_of_command', 'basics': ['shield_bash', 'stalwart']},
              {'defn': 'gretel', 'sig': 'crumb_trail', 'basics': ['feint', 'cleave']}],
  'artifacts': ['magic_mirror', 'holy_grail', 'bluebeards_key']},
 {'name': 'Shock Doctrine',
  'usage': 'Spread Shock early, then let Witch and Asha turn status density into lethal damage. This punishes slow, '
           'buff-heavy teams especially well.',
  'members': [{'defn': 'hunold_the_piper', 'sig': 'haunting_rhythm', 'basics': ['sucker_punch', 'post_bounty']},
              {'defn': 'witch_of_the_woods', 'sig': 'crawling_abode', 'basics': ['thunder_call', 'ominous_gale']},
              {'defn': 'sea_wench_asha', 'sig': 'abyssal_call', 'basics': ['dark_grasp', 'blood_pact']}],
  'artifacts': ['cursed_needle', 'misericorde_artifact', 'last_prism']},
 {'name': 'Silver Tempo',
  'usage': 'Roland and Aldric make Hare\'s extra-action turns safe enough to force repeatedly. Hard to kill, hard to '
           'outspeed, and very stable.',
  'members': [{'defn': 'sir_roland', 'sig': 'shimmering_valor', 'basics': ['shield_bash', 'stalwart']},
              {'defn': 'march_hare', 'sig': 'rabbit_hole', 'basics': ['arcane_wave', 'breakthrough']},
              {'defn': 'aldric_lost_lamb', 'sig': 'sanctuary', 'basics': ['heal', 'bless']}],
  'artifacts': ['holy_grail', 'bluebeards_key', 'winged_sandals']},
 {'name': 'Root Tribunal',
  'usage': 'This is the most direct anti-movement root shell in the set. Once a target is trapped, the team keeps them '
           'trapped until they die.',
  'members': [{'defn': 'rapunzel', 'sig': 'golden_snare', 'basics': ['edict', 'impose']},
              {'defn': 'briar_rose', 'sig': 'creeping_doubt', 'basics': ['trapping_blow', 'hunters_mark']},
              {'defn': 'green_knight', 'sig': 'heros_bargain', 'basics': ['command', 'decree']}],
  'artifacts': ['cursed_needle', 'magic_mirror', 'nettle_smock']},
 {'name': 'Expose Execution',
  'usage': 'Expose first, then immediately convert with Jack or Robin. Simple, brutal, and very effective into '
           'low-defense backlines.',
  'members': [{'defn': 'lucky_constantine', 'sig': 'feline_gambit', 'basics': ['post_bounty', 'sucker_punch']},
              {'defn': 'little_jack', 'sig': 'skyfall', 'basics': ['strike', 'cleave']},
              {'defn': 'robin_hooded_avenger', 'sig': 'snipe_shot', 'basics': ['hawkshot', 'hunters_badge']}],
  'artifacts': ['excalibur', 'melusines_knife', 'winged_sandals']},
 {'name': 'Burn Spiral',
  'usage': 'Burn spreads quickly and every heal keeps the burn plan alive. Very strong into teams that lack cleansing '
           'or fast kill pressure.',
  'members': [{'defn': 'gretel', 'sig': 'hot_mitts', 'basics': ['strike', 'rend']},
              {'defn': 'ashen_ella', 'sig': 'crowstorm', 'basics': ['fire_blast', 'ominous_gale']},
              {'defn': 'matchstick_liesl', 'sig': 'cinder_blessing', 'basics': ['heal', 'bless']}],
  'artifacts': ['misericorde_artifact', 'cursed_needle', 'bluebeards_key']},
 {'name': 'Attrition Engine',
  'usage': 'This is pure durability. Use it when you want to outlast burst teams and slowly win through reflected and '
           'incidental value.',
  'members': [{'defn': 'porcus_iii', 'sig': 'porcine_honor', 'basics': ['shield_bash', 'stalwart']},
              {'defn': 'lady_of_reflections', 'sig': 'lakes_gift', 'basics': ['shield_bash', 'armored']},
              {'defn': 'aldric_lost_lamb', 'sig': 'benefactor', 'basics': ['heal', 'protection']}],
  'artifacts': ['holy_grail', 'bluebeards_key', 'red_hood']},
 {'name': 'Duel And Deliver',
  'usage': 'Force bad attack lines into retaliations and champion punishment. This team is best when you can predict '
           'where the enemy must attack.',
  'members': [{'defn': 'green_knight', 'sig': 'awaited_blow', 'basics': ['impose', 'command']},
              {'defn': 'prince_charming', 'sig': 'chosen_one', 'basics': ['summons', 'decree']},
              {'defn': 'reynard', 'sig': 'feign_weakness', 'basics': ['riposte', 'fleetfooted']}],
  'artifacts': ['excalibur', 'magic_mirror', 'golden_fleece']},
 {'name': 'Puppet Pressure',
  'usage': 'Hare and Asha create disruption while Pinocchio scales into a real carry. High-skill, high-reward, and '
           'nasty into passive teams.',
  'members': [{'defn': 'pinocchio', 'sig': 'become_real', 'basics': ['dark_grasp', 'blood_pact']},
              {'defn': 'sea_wench_asha', 'sig': 'misappropriate', 'basics': ['soul_gaze', 'void_step']},
              {'defn': 'march_hare', 'sig': 'tempus_fugit', 'basics': ['thunder_call', 'ominous_gale']}],
  'artifacts': ['last_prism', 'selkies_skin', 'goose_quill']},
 {'name': 'Backline Jail',
  'usage': 'The whole point is to make the enemy backline unsafe and immobile. Once spotlighted or rooted, they are '
           'usually stuck under Robin and Hunold pressure.',
  'members': [{'defn': 'robin_hooded_avenger', 'sig': 'bring_down', 'basics': ['hawkshot', 'trapping_blow']},
              {'defn': 'briar_rose', 'sig': 'garden_of_thorns', 'basics': ['volley', 'trapping_blow']},
              {'defn': 'hunold_the_piper', 'sig': 'dying_dance', 'basics': ['sucker_punch', 'fleetfooted']}],
  'artifacts': ['cursed_needle', 'last_prism', 'misericorde_artifact']},
 {'name': 'Swap Tax',
  'usage': 'Every swap produces value for you and cost for them. This team is amazing into players who rely on '
           'repositioning to stay safe.',
  'members': [{'defn': 'prince_charming', 'sig': 'chosen_one', 'basics': ['command', 'summons']},
              {'defn': 'sir_roland', 'sig': 'banner_of_command', 'basics': ['shield_bash', 'armored']},
              {'defn': 'reynard', 'sig': 'cutpurse', 'basics': ['sneak_attack', 'fleetfooted']}],
  'artifacts': ['magic_mirror', 'excalibur', 'godmothers_wand']},
 {'name': 'Birdsong Bastion',
  'usage': 'A slow fortress team. Use it to neutralize status and grind opponents out once Aurora starts compounding '
           'bird value.',
  'members': [{'defn': 'snowkissed_aurora', 'sig': 'birdsong', 'basics': ['medic', 'protection']},
              {'defn': 'aldric_lost_lamb', 'sig': 'sanctuary', 'basics': ['heal', 'bless']},
              {'defn': 'sir_roland', 'sig': 'shimmering_valor', 'basics': ['shield_bash', 'stalwart']}],
  'artifacts': ['divine_apple', 'holy_grail', 'bluebeards_key']},
 {'name': 'Malice Furnace',
  'usage': 'This is the greedier warlock trio, but it scales absurdly well if the opponent cannot close. Manage Malice '
           'carefully and it takes over.',
  'members': [{'defn': 'rumpelstiltskin', 'sig': 'spinning_wheel', 'basics': ['dark_grasp', 'blood_pact']},
              {'defn': 'pinocchio', 'sig': 'wooden_wallop', 'basics': ['soul_gaze', 'cursed_armor']},
              {'defn': 'sea_wench_asha', 'sig': 'faustian_bargain', 'basics': ['dark_grasp', 'void_step']}],
  'artifacts': ['achilles_spear', 'selkies_skin', 'goose_quill']},
 {'name': 'Fae Burst',
  'usage': 'Ella and Hare set up one decisive burst window for Jack. It is explosive and rewards precise sequencing '
           'more than prolonged brawling.',
  'members': [{'defn': 'ashen_ella', 'sig': 'fae_blessing', 'basics': ['arcane_wave', 'breakthrough']},
              {'defn': 'little_jack', 'sig': 'skyfall', 'basics': ['strike', 'cleave']},
              {'defn': 'march_hare', 'sig': 'nebulous_ides', 'basics': ['thunder_call', 'ominous_gale']}],
  'artifacts': ['excalibur', 'winged_sandals', 'goose_quill']},
 {'name': 'Anti-Frontline Grind',
  'usage': 'Beat the frontline down until the rest of the formation falls apart. Very good into teams that overinvest '
           'in one tank.',
  'members': [{'defn': 'frederic', 'sig': 'on_the_hunt', 'basics': ['hunters_mark', 'hunters_badge']},
              {'defn': 'lady_of_reflections', 'sig': 'drown_in_the_loch', 'basics': ['shield_bash', 'condemn']},
              {'defn': 'risa_redcloak', 'sig': 'crimson_fury', 'basics': ['rend', 'cleave']}],
  'artifacts': ['achilles_spear', 'holy_grail', 'red_hood']},
 {'name': 'Revival Lock',
  'usage': 'This is a stubborn anti-attrition team that punishes trades and survives the first collapse. Best into '
           'teams that need a clean second kill to finish games.',
  'members': [{'defn': 'matchstick_liesl', 'sig': 'flame_of_renewal', 'basics': ['heal', 'protection']},
              {'defn': 'lady_of_reflections', 'sig': 'postmortem_passage', 'basics': ['shield_bash', 'armored']},
              {'defn': 'rapunzel', 'sig': 'ivory_tower', 'basics': ['summons', 'command']}],
  'artifacts': ['enchanted_lamp', 'bluebeards_key', 'divine_apple']}]

RANKED_AI_TEAM_META = {
    "Blood Current": {"rating": 1550, "weight": 2.0},
    "Tempo Chapel": {"rating": 1500, "weight": 1.9},
    "Rootbreaker Court": {"rating": 1360, "weight": 1.35},
    "Phantom Carriage": {"rating": 1140, "weight": 0.95},
    "Marked Quarry": {"rating": 1475, "weight": 1.75},
    "Kiln And Sea": {"rating": 1340, "weight": 1.35},
    "Avalon Hunt": {"rating": 1180, "weight": 1.0},
    "Radiant Briars": {"rating": 1080, "weight": 1.1},
    "Pursuit Lock": {"rating": 1320, "weight": 1.35},
    "Storm Chapel": {"rating": 1490, "weight": 1.8},
    "Oven Garden": {"rating": 1335, "weight": 1.35},
    "Puppet Midnight": {"rating": 980, "weight": 0.75},
    "Royal Crossfire": {"rating": 1160, "weight": 1.0},
    "Boiling Deep": {"rating": 1120, "weight": 0.95},
    "Trial By Gold": {"rating": 1210, "weight": 1.1},
    "Ashen Lullaby": {"rating": 1040, "weight": 1.05},
    "Blood Ledger": {"rating": 1380, "weight": 1.4},
    "Cloudburst Loop": {"rating": 1280, "weight": 1.2},
    "Crumb Kingdom": {"rating": 1260, "weight": 1.15},
    "Smoke At Midnight": {"rating": 1060, "weight": 0.85},
    "Fox's Coronation": {"rating": 1085, "weight": 0.85},
    "Fortress Sabbath": {"rating": 1240, "weight": 1.0},
    "Avalon Quarry": {"rating": 1175, "weight": 0.95},
    "Tower Wake": {"rating": 1020, "weight": 1.0},
    "Hit And Run": {"rating": 1680, "weight": 2.25},
    "Shock Doctrine": {"rating": 1530, "weight": 1.85},
    "Silver Tempo": {"rating": 1580, "weight": 2.1},
    "Root Tribunal": {"rating": 1540, "weight": 1.9},
    "Expose Execution": {"rating": 1560, "weight": 1.95},
    "Burn Spiral": {"rating": 1510, "weight": 1.85},
    "Attrition Engine": {"rating": 1410, "weight": 1.55},
    "Duel And Deliver": {"rating": 1190, "weight": 1.05},
    "Puppet Pressure": {"rating": 990, "weight": 0.8},
    "Backline Jail": {"rating": 1310, "weight": 1.25},
    "Swap Tax": {"rating": 1370, "weight": 1.45},
    "Birdsong Bastion": {"rating": 1010, "weight": 1.0},
    "Malice Furnace": {"rating": 950, "weight": 0.7},
    "Fae Burst": {"rating": 1430, "weight": 1.55},
    "Anti-Frontline Grind": {"rating": 1450, "weight": 1.65},
    "Revival Lock": {"rating": 1230, "weight": 1.15},
}
