from __future__ import annotations

from dataclasses import dataclass

from settings import SLOT_BACK_LEFT, SLOT_BACK_RIGHT, SLOT_FRONT


@dataclass(frozen=True)
class AdventurerAIProfile:
    base_power: int
    reliability: int
    complexity: int
    role_tags: tuple[str, ...]
    shell_tags: tuple[str, ...]
    matchup_tags: tuple[str, ...]
    good_into: tuple[str, ...]
    bad_into: tuple[str, ...]
    preferred_classes: tuple[str, ...]
    preferred_skills: dict[str, tuple[str, ...]]
    preferred_weapons: tuple[str, ...]
    preferred_artifacts: tuple[str, ...]
    position_scores: dict[str, int]


def _profile(
    *,
    base_power: int,
    reliability: int,
    complexity: int,
    roles: tuple[str, ...],
    shells: tuple[str, ...],
    matchup: tuple[str, ...],
    good_into: tuple[str, ...],
    bad_into: tuple[str, ...],
    classes: tuple[str, ...],
    skills: dict[str, tuple[str, ...]],
    weapons: tuple[str, ...],
    artifacts: tuple[str, ...],
    front: int,
    back_left: int,
    back_right: int,
) -> AdventurerAIProfile:
    return AdventurerAIProfile(
        base_power=base_power,
        reliability=reliability,
        complexity=complexity,
        role_tags=roles,
        shell_tags=shells,
        matchup_tags=matchup,
        good_into=good_into,
        bad_into=bad_into,
        preferred_classes=classes,
        preferred_skills=skills,
        preferred_weapons=weapons,
        preferred_artifacts=artifacts,
        position_scores={
            SLOT_FRONT: front,
            SLOT_BACK_LEFT: back_left,
            SLOT_BACK_RIGHT: back_right,
        },
    )


DEFAULT_CLASS_SKILL_ORDER = {
    "Fighter": ("martial", "vanguard", "inevitable"),
    "Rogue": ("covert", "fleetfooted", "assassin"),
    "Warden": ("bulwark", "vigilant", "stalwart"),
    "Mage": ("arcane", "overflow", "archmage"),
    "Ranger": ("deadeye", "tactical", "armed"),
    "Cleric": ("healer", "medic", "protector"),
}


CLASS_SKILL_TAGS = {
    "martial": {"melee", "damage", "burst"},
    "inevitable": {"strike_meter", "snowball"},
    "vanguard": {"melee", "reach", "bonus_action", "aggression"},
    "covert": {"swap", "bonus_action", "mobility"},
    "fleetfooted": {"survival", "anti_burst"},
    "assassin": {"reach", "punish_idle"},
    "stalwart": {"anti_displacement", "frontline"},
    "bulwark": {"frontline", "durability"},
    "vigilant": {"swap", "guard", "durability"},
    "arcane": {"magic", "damage"},
    "overflow": {"magic", "frontline", "tempo"},
    "archmage": {"switch", "spell_tempo"},
    "deadeye": {"ranged", "damage"},
    "armed": {"ranged", "ammo", "switch"},
    "tactical": {"switch", "bonus_action"},
    "healer": {"healing", "sustain"},
    "medic": {"healing", "cleanse", "anti_status"},
    "protector": {"team_defense", "support"},
}


ARTIFACT_TAGS = {
    "holy_grail": {"sustain", "cleanse", "patch"},
    "winged_sandals": {"mobility", "swap", "tempo"},
    "lightning_helm": {"setup", "shock", "burst"},
    "golden_fleece": {"sustain", "attack_buff", "patch"},
    "arcane_hourglass": {"anti_burst", "rescue", "stall"},
    "naiads_knife": {"setup", "expose", "burst"},
    "last_prism": {"magic", "damage", "finisher"},
    "misericorde": {"finisher", "status_payoff"},
    "selkies_skin": {"anti_burst", "rescue"},
    "red_hood": {"lifesteal", "sustain", "damage"},
    "enchanted_lamp": {"anti_burst", "death_insurance", "rescue"},
    "magic_mirror": {"anti_spell", "rescue"},
    "nettle_smock": {"anti_burst", "reflect", "anti_heal"},
    "goose_quill": {"ultimate", "tempo"},
    "cursed_spindle": {"status_extension", "setup"},
    "bluebeards_key": {"anti_guard", "anti_defense"},
    "sun_gods_banner": {"guard", "frontline", "anti_burst"},
    "dire_wolf_spine": {"melee", "weaken", "burst"},
    "soaring_crown": {"reach", "ranged", "ammo"},
    "fading_diadem": {"sustain", "guard", "patch"},
    "iron_rosary": {"cleanse", "sustain", "anti_status"},
    "dragons_horn": {"damage", "spotlight", "reach"},
    "bottled_clouds": {"spread", "damage", "reach"},
    "glass_slipper": {"mobility", "swap", "spell_tempo"},
    "black_torch": {"snowball", "finisher", "sustain"},
    "cornucopia": {"swap", "sustain", "mobility"},
    "all_mill": {"anti_root", "speed", "durability"},
    "paradox_rings": {"swap", "spell_tempo", "mobility"},
    "jade_rabbit": {"lifesteal", "ammo", "tempo"},
    "swan_cloak": {"anti_burst", "swap", "mobility"},
}


ADVENTURER_AI = {
    "red_blanchette": _profile(
        base_power=76,
        reliability=63,
        complexity=70,
        roles=("burst_finisher", "status_payoff", "snowball", "frontline_pivot"),
        shells=("expose", "bloodied", "burst"),
        matchup=("fragile_backline", "swap_punish"),
        good_into=("swap_heavy", "fragile_backline"),
        bad_into=("hard_control",),
        classes=("Fighter", "Mage", "Rogue"),
        skills={
            "Fighter": ("martial", "vanguard", "inevitable"),
            "Mage": ("arcane", "overflow", "archmage"),
            "Rogue": ("covert", "fleetfooted", "assassin"),
        },
        weapons=("enchanted_shackles", "stomach_splitter"),
        artifacts=("naiads_knife", "red_hood", "enchanted_lamp", "lightning_helm"),
        front=76,
        back_left=60,
        back_right=64,
    ),
    "little_jack": _profile(
        base_power=82,
        reliability=76,
        complexity=46,
        roles=("burst_finisher", "frontline_breaker", "anti_tank", "frontline_ready"),
        shells=("burst", "expose"),
        matchup=("tank", "frontline"),
        good_into=("tank", "guard_heavy"),
        bad_into=("root_heavy",),
        classes=("Fighter", "Warden"),
        skills={
            "Fighter": ("martial", "vanguard", "inevitable"),
            "Warden": ("bulwark", "stalwart", "vigilant"),
        },
        weapons=("skyfall", "giants_harp"),
        artifacts=("dire_wolf_spine", "dragons_horn", "naiads_knife", "red_hood"),
        front=84,
        back_left=68,
        back_right=44,
    ),
    "witch_hunter_gretel": _profile(
        base_power=72,
        reliability=72,
        complexity=54,
        roles=("burn_enabler", "snowball", "chip_damage", "anti_heal"),
        shells=("burn", "attrition"),
        matchup=("heal_heavy", "slow_frontline"),
        good_into=("heal_heavy",),
        bad_into=("burst_focus",),
        classes=("Fighter", "Ranger"),
        skills={
            "Fighter": ("martial", "inevitable", "vanguard"),
            "Ranger": ("deadeye", "armed", "tactical"),
        },
        weapons=("hot_mitts", "crumb_shot"),
        artifacts=("cursed_spindle", "black_torch", "red_hood", "fading_diadem"),
        front=70,
        back_left=72,
        back_right=58,
    ),
    "lucky_constantine": _profile(
        base_power=74,
        reliability=61,
        complexity=67,
        roles=("expose_enabler", "swap_engine", "backline_reach", "fragile"),
        shells=("expose", "swap", "burst"),
        matchup=("fragile_backline", "idle_punish"),
        good_into=("fragile_backline", "slow_backline"),
        bad_into=("tank", "burst_focus"),
        classes=("Rogue", "Fighter"),
        skills={
            "Rogue": ("covert", "assassin", "fleetfooted"),
            "Fighter": ("martial", "vanguard", "inevitable"),
        },
        weapons=("fortuna", "cat_o_nine"),
        artifacts=("glass_slipper", "naiads_knife", "enchanted_lamp", "selkies_skin"),
        front=54,
        back_left=66,
        back_right=82,
    ),
    "hunold_the_piper": _profile(
        base_power=84,
        reliability=79,
        complexity=59,
        roles=("shock_engine", "shock_payoff", "control_anchor", "backline_reach"),
        shells=("shock", "control"),
        matchup=("slow_frontline", "fragile_backline", "spell_heavy"),
        good_into=("slow_frontline", "fragile_backline"),
        bad_into=("hard_cleanse",),
        classes=("Mage", "Ranger"),
        skills={
            "Mage": ("arcane", "overflow", "archmage"),
            "Ranger": ("deadeye", "armed", "tactical"),
        },
        weapons=("lightning_rod", "golden_fiddle"),
        artifacts=("lightning_helm", "cursed_spindle", "bottled_clouds", "soaring_crown"),
        front=60,
        back_left=84,
        back_right=86,
    ),
    "sir_roland": _profile(
        base_power=88,
        reliability=91,
        complexity=34,
        roles=("primary_tank", "guard_support", "taunt", "expose_enabler"),
        shells=("protect", "expose"),
        matchup=("frontline", "burst_support"),
        good_into=("burst_focus", "fragile_backline"),
        bad_into=("anti_guard",),
        classes=("Warden", "Fighter"),
        skills={
            "Warden": ("bulwark", "vigilant", "stalwart"),
            "Fighter": ("vanguard", "martial", "inevitable"),
        },
        weapons=("pure_silver_shield", "pure_gold_lance"),
        artifacts=("sun_gods_banner", "holy_grail", "golden_fleece", "nettle_smock"),
        front=98,
        back_left=84,
        back_right=38,
    ),
    "porcus_iii": _profile(
        base_power=80,
        reliability=89,
        complexity=36,
        roles=("primary_tank", "anti_burst", "weaken_support", "stall_anchor"),
        shells=("protect", "stall"),
        matchup=("burst_focus", "melee_heavy"),
        good_into=("burst_focus", "melee_heavy"),
        bad_into=("anti_guard", "sustain_heavy"),
        classes=("Warden", "Ranger"),
        skills={
            "Warden": ("bulwark", "stalwart", "vigilant"),
            "Ranger": ("deadeye", "armed", "tactical"),
        },
        weapons=("crafty_wall", "mortar_mortar"),
        artifacts=("sun_gods_banner", "holy_grail", "golden_fleece", "nettle_smock"),
        front=96,
        back_left=88,
        back_right=30,
    ),
    "lady_of_reflections": _profile(
        base_power=73,
        reliability=73,
        complexity=74,
        roles=("swap_engine", "anti_burst", "death_insurance", "tempo_support"),
        shells=("swap", "protect"),
        matchup=("burst_focus", "spell_heavy"),
        good_into=("burst_focus",),
        bad_into=("anti_swap",),
        classes=("Warden", "Rogue", "Cleric"),
        skills={
            "Warden": ("vigilant", "bulwark", "stalwart"),
            "Rogue": ("covert", "fleetfooted", "assassin"),
            "Cleric": ("protector", "healer", "medic"),
        },
        weapons=("lantern_of_avalon", "excalibur_doc"),
        artifacts=("glass_slipper", "winged_sandals", "holy_grail", "selkies_skin"),
        front=72,
        back_left=78,
        back_right=70,
    ),
    "ashen_ella": _profile(
        base_power=78,
        reliability=60,
        complexity=71,
        roles=("spread_pressure", "burn_enabler", "fragile", "magic_carry"),
        shells=("burn", "spread"),
        matchup=("slow_frontline", "clump"),
        good_into=("slow_frontline",),
        bad_into=("burst_focus", "anti_magic"),
        classes=("Mage", "Rogue"),
        skills={
            "Mage": ("overflow", "arcane", "archmage"),
            "Rogue": ("fleetfooted", "covert", "assassin"),
        },
        weapons=("obsidian_slippers", "dusty_broom"),
        artifacts=("last_prism", "cursed_spindle", "magic_mirror", "arcane_hourglass"),
        front=72,
        back_left=64,
        back_right=80,
    ),
    "march_hare": _profile(
        base_power=86,
        reliability=73,
        complexity=82,
        roles=("shock_engine", "tempo_engine", "bonus_action_user", "spell_loop"),
        shells=("shock", "spell", "tempo"),
        matchup=("spell_heavy", "slow_frontline"),
        good_into=("slow_frontline", "stall_heavy"),
        bad_into=("burst_focus",),
        classes=("Mage", "Rogue"),
        skills={
            "Mage": ("overflow", "archmage", "arcane"),
            "Rogue": ("covert", "fleetfooted", "assassin"),
        },
        weapons=("stitch_in_time", "cracked_stopwatch"),
        artifacts=("arcane_hourglass", "last_prism", "glass_slipper", "goose_quill"),
        front=74,
        back_left=80,
        back_right=84,
    ),
    "briar_rose": _profile(
        base_power=83,
        reliability=80,
        complexity=56,
        roles=("root_enabler", "spread_pressure", "control_anchor", "anti_swap"),
        shells=("root", "control"),
        matchup=("swap_heavy", "melee_heavy"),
        good_into=("swap_heavy", "melee_heavy"),
        bad_into=("hard_cleanse",),
        classes=("Ranger", "Rogue"),
        skills={
            "Ranger": ("deadeye", "tactical", "armed"),
            "Rogue": ("covert", "fleetfooted", "assassin"),
        },
        weapons=("thorn_snare", "spindle_bow"),
        artifacts=("soaring_crown", "cursed_spindle", "dragons_horn", "bottled_clouds"),
        front=42,
        back_left=82,
        back_right=84,
    ),
    "wayward_humbert": _profile(
        base_power=71,
        reliability=63,
        complexity=68,
        roles=("weapon_switch_user", "ranged_pressure", "self_sustain", "high_variance"),
        shells=("switch", "tempo"),
        matchup=("fragile_backline",),
        good_into=("fragile_backline",),
        bad_into=("reflect", "anti_burst"),
        classes=("Ranger", "Rogue"),
        skills={
            "Ranger": ("tactical", "armed", "deadeye"),
            "Rogue": ("fleetfooted", "covert", "assassin"),
        },
        weapons=("pallid_musket", "convicted_shotgun"),
        artifacts=("soaring_crown", "dragons_horn", "selkies_skin", "red_hood"),
        front=48,
        back_left=68,
        back_right=82,
    ),
    "robin_hooded_avenger": _profile(
        base_power=85,
        reliability=82,
        complexity=48,
        roles=("spread_pressure", "spotlight_enabler", "anti_guard", "backline_reach"),
        shells=("root", "spread", "reach"),
        matchup=("guard_heavy", "fragile_backline"),
        good_into=("guard_heavy", "fragile_backline"),
        bad_into=("hard_cleanse",),
        classes=("Ranger", "Fighter", "Rogue"),
        skills={
            "Ranger": ("deadeye", "armed", "tactical"),
            "Fighter": ("martial", "inevitable", "vanguard"),
            "Rogue": ("assassin", "fleetfooted", "covert"),
        },
        weapons=("the_flock", "kingmaker"),
        artifacts=("soaring_crown", "dragons_horn", "bottled_clouds", "red_hood"),
        front=56,
        back_left=78,
        back_right=86,
    ),
    "matchbox_liesl": _profile(
        base_power=84,
        reliability=89,
        complexity=44,
        roles=("healer", "burn_payoff", "anti_burst", "death_insurance"),
        shells=("burn", "sustain", "attrition"),
        matchup=("burn_heavy", "attrition"),
        good_into=("burn_heavy", "attrition"),
        bad_into=("anti_heal",),
        classes=("Cleric", "Mage"),
        skills={
            "Cleric": ("healer", "medic", "protector"),
            "Mage": ("arcane", "overflow", "archmage"),
        },
        weapons=("matchsticks", "eternal_torch"),
        artifacts=("iron_rosary", "fading_diadem", "holy_grail", "cursed_spindle"),
        front=58,
        back_left=72,
        back_right=84,
    ),
    "the_good_beast": _profile(
        base_power=82,
        reliability=87,
        complexity=49,
        roles=("primary_tank", "carry_support", "healer", "guard_support"),
        shells=("protect", "sustain"),
        matchup=("burst_focus", "fragile_backline"),
        good_into=("burst_focus",),
        bad_into=("anti_heal",),
        classes=("Cleric", "Warden"),
        skills={
            "Cleric": ("protector", "healer", "medic"),
            "Warden": ("bulwark", "vigilant", "stalwart"),
        },
        weapons=("dinner_bell", "rosebush_sword"),
        artifacts=("holy_grail", "golden_fleece", "fading_diadem", "iron_rosary"),
        front=90,
        back_left=82,
        back_right=52,
    ),
    "the_green_knight": _profile(
        base_power=77,
        reliability=73,
        complexity=65,
        roles=("swap_engine", "duel_control", "bonus_action_user", "frontline_pivot"),
        shells=("swap", "duel"),
        matchup=("single_carry", "fragile_backline"),
        good_into=("single_carry", "fragile_backline"),
        bad_into=("wide_control",),
        classes=("Warden", "Fighter", "Ranger"),
        skills={
            "Warden": ("vigilant", "bulwark", "stalwart"),
            "Fighter": ("vanguard", "martial", "inevitable"),
            "Ranger": ("deadeye", "tactical", "armed"),
        },
        weapons=("the_answer", "the_search"),
        artifacts=("winged_sandals", "dragons_horn", "sun_gods_banner", "nettle_smock"),
        front=82,
        back_left=78,
        back_right=56,
    ),
    "rapunzel_the_golden": _profile(
        base_power=81,
        reliability=80,
        complexity=58,
        roles=("root_payoff", "healer", "melee_reach", "bruiser"),
        shells=("root", "sustain"),
        matchup=("melee_heavy", "slow_frontline"),
        good_into=("melee_heavy", "slow_frontline"),
        bad_into=("burst_focus",),
        classes=("Fighter", "Warden", "Cleric"),
        skills={
            "Fighter": ("vanguard", "martial", "inevitable"),
            "Warden": ("bulwark", "vigilant", "stalwart"),
            "Cleric": ("healer", "protector", "medic"),
        },
        weapons=("golden_snare", "ivory_tower"),
        artifacts=("holy_grail", "winged_sandals", "bluebeards_key", "golden_fleece"),
        front=84,
        back_left=80,
        back_right=50,
    ),
    "pinocchio_cursed_puppet": _profile(
        base_power=70,
        reliability=56,
        complexity=74,
        roles=("scaling_carry", "self_ramp", "fragile", "frontline_growth"),
        shells=("scaling", "tempo"),
        matchup=("slow_frontline",),
        good_into=("slow_frontline",),
        bad_into=("burst_focus", "hard_control"),
        classes=("Mage", "Fighter", "Rogue"),
        skills={
            "Mage": ("arcane", "overflow", "archmage"),
            "Fighter": ("martial", "vanguard", "inevitable"),
            "Rogue": ("fleetfooted", "covert", "assassin"),
        },
        weapons=("string_cutter", "wooden_club"),
        artifacts=("last_prism", "selkies_skin", "enchanted_lamp", "nettle_smock"),
        front=66,
        back_left=62,
        back_right=78,
    ),
    "rumpelstiltskin": _profile(
        base_power=73,
        reliability=62,
        complexity=78,
        roles=("stat_manipulator", "burst_spellcaster", "synergy_amplifier", "setup_dependent"),
        shells=("buff", "debuff", "tempo"),
        matchup=("buff_heavy", "guard_heavy"),
        good_into=("buff_heavy", "guard_heavy"),
        bad_into=("burst_focus",),
        classes=("Mage", "Ranger", "Rogue"),
        skills={
            "Mage": ("arcane", "archmage", "overflow"),
            "Ranger": ("tactical", "deadeye", "armed"),
            "Rogue": ("covert", "fleetfooted", "assassin"),
        },
        weapons=("devils_contract", "spinning_wheel"),
        artifacts=("goose_quill", "cursed_spindle", "last_prism", "bottled_clouds"),
        front=50,
        back_left=68,
        back_right=80,
    ),
    "sea_wench_asha": _profile(
        base_power=75,
        reliability=67,
        complexity=72,
        roles=("anti_caster", "spell_theft", "adaptive_damage", "volatile_utility"),
        shells=("anti_spell", "magic"),
        matchup=("spell_heavy",),
        good_into=("spell_heavy",),
        bad_into=("burst_focus",),
        classes=("Mage", "Rogue"),
        skills={
            "Mage": ("arcane", "overflow", "archmage"),
            "Rogue": ("fleetfooted", "covert", "assassin"),
        },
        weapons=("frost_scepter", "mirror_blade"),
        artifacts=("magic_mirror", "last_prism", "arcane_hourglass", "goose_quill"),
        front=58,
        back_left=72,
        back_right=84,
    ),
    "destitute_vasilisa": _profile(
        base_power=79,
        reliability=82,
        complexity=69,
        roles=("guard_support", "healer", "spotlight_enabler", "control_anchor"),
        shells=("guard", "sustain", "spotlight"),
        matchup=("burst_focus", "spell_heavy"),
        good_into=("burst_focus",),
        bad_into=("anti_heal",),
        classes=("Cleric", "Mage", "Warden"),
        skills={
            "Cleric": ("healer", "protector", "medic"),
            "Mage": ("arcane", "archmage", "overflow"),
            "Warden": ("vigilant", "bulwark", "stalwart"),
        },
        weapons=("guiding_doll", "skull_lantern"),
        artifacts=("paradox_rings", "jade_rabbit", "holy_grail", "fading_diadem"),
        front=72,
        back_left=82,
        back_right=80,
    ),
    "ali_baba": _profile(
        base_power=83,
        reliability=75,
        complexity=73,
        roles=("anti_caster", "burn_enabler", "bonus_action_user", "backline_reach"),
        shells=("burn", "control", "tempo"),
        matchup=("spell_heavy", "fragile_backline"),
        good_into=("spell_heavy", "fragile_backline"),
        bad_into=("tank",),
        classes=("Rogue", "Mage", "Fighter"),
        skills={
            "Rogue": ("assassin", "fleetfooted", "covert"),
            "Mage": ("arcane", "archmage", "overflow"),
            "Fighter": ("vanguard", "martial", "inevitable"),
        },
        weapons=("jar_of_oil", "thiefs_dagger"),
        artifacts=("swan_cloak", "cursed_spindle", "lightning_helm", "red_hood"),
        front=68,
        back_left=84,
        back_right=86,
    ),
    "maui_sunthief": _profile(
        base_power=88,
        reliability=90,
        complexity=55,
        roles=("primary_tank", "frontline_breaker", "anti_burst", "bruiser"),
        shells=("protect", "frontline", "buff"),
        matchup=("tank", "frontline"),
        good_into=("tank", "burst_focus"),
        bad_into=("anti_guard",),
        classes=("Warden", "Fighter"),
        skills={
            "Warden": ("bulwark", "stalwart", "vigilant"),
            "Fighter": ("martial", "vanguard", "inevitable"),
        },
        weapons=("whale_jaw_hook", "ancestral_warclub"),
        artifacts=("all_mill", "cornucopia", "sun_gods_banner", "golden_fleece"),
        front=97,
        back_left=70,
        back_right=34,
    ),
    "kama_the_honeyed": _profile(
        base_power=80,
        reliability=77,
        complexity=66,
        roles=("spotlight_enabler", "ranged_pressure", "shock_engine", "backline_reach"),
        shells=("spotlight", "ranged", "ammo"),
        matchup=("fragile_backline", "slow_frontline"),
        good_into=("fragile_backline", "slow_frontline"),
        bad_into=("hard_cleanse",),
        classes=("Ranger", "Rogue", "Mage"),
        skills={
            "Ranger": ("deadeye", "armed", "tactical"),
            "Rogue": ("assassin", "fleetfooted", "covert"),
            "Mage": ("arcane", "archmage", "overflow"),
        },
        weapons=("sugarcane_bow", "the_stinger"),
        artifacts=("jade_rabbit", "soaring_crown", "dragons_horn", "cornucopia"),
        front=56,
        back_left=82,
        back_right=84,
    ),
}


def artifact_preference_score(profile: AdventurerAIProfile, artifact_id: str) -> int:
    if artifact_id not in profile.preferred_artifacts:
        return 0
    return max(0, 16 - profile.preferred_artifacts.index(artifact_id) * 4)


def skill_preference_score(profile: AdventurerAIProfile, class_name: str, skill_id: str) -> int:
    ordered = profile.preferred_skills.get(class_name) or DEFAULT_CLASS_SKILL_ORDER[class_name]
    if skill_id not in ordered:
        return 0
    return max(0, 12 - ordered.index(skill_id) * 4)


def weapon_preference_score(profile: AdventurerAIProfile, weapon_id: str) -> int:
    if weapon_id not in profile.preferred_weapons:
        return 0
    return max(0, 14 - profile.preferred_weapons.index(weapon_id) * 6)
